
# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /

COPY apiserver .
COPY bin/swagger-ui/dist bin/swagger-ui/dist

USER nonroot:nonroot

ENTRYPOINT ["/apiserver"]
