
# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /

RUN mkdir -p bin/swagger-ui
COPY apiserver .
COPY /home/jenkins/go/pkg/mod/github.com/swagger-api/swagger-ui/dist bin/swagger-ui/dist

USER nonroot:nonroot

ENTRYPOINT ["/apiserver"]
